//
//  File.swift
//  BombGame
//
//  Created by Marat Fakhrizhanov on 11.02.2025.
//

import Foundation

enum Category {
    case general
    case sport
    case life
    case celebrities
    case moviesAndArt
    case nature
}

struct Question: Identifiable {
    let id: UUID = UUID()
    let question: String
    let category: Category
    
    static let questions: [Question] = [
        
        //General
        Question(question: "Какой твой самый неожиданный талант?", category: .general),
        Question(question: "Какое важное жизненное правило ты для себя установил?", category: .general),
        Question(question: "Что для тебя значит успех?", category: .general),
        Question(question: "Как ты справляешься со стрессом?", category: .general),
        Question(question: "Какая у тебя мечта, о которой пока мало кто знает?", category: .general),
        Question(question: "Какие страны вы хотели бы посетить?", category: .general),
        Question(question: "Какие книги вам нравятся?", category: .general),
        Question(question: "Какие животные живут в джунглях?", category: .general),
        Question(question: "Какие фрукты вы любите?", category: .general),
        Question(question: "Какие фильмы можно пересматривать снова и снова?", category: .general),
        Question(question: "Какие музыкальные жанры вам известны?", category: .general),
        Question(question: "Какие качества важны в друге?", category: .general),
        Question(question: "Какие праздники отмечают в разных странах?", category: .general),
        Question(question: "Какие известные изобретения изменили мир?", category: .general),
        Question(question: "Какие языки вы знаете?", category: .general),
        // Sport
        Question(question: "Как есть виды восстанавления после тренировок?", category: .sport),
        Question(question: "Как ты считаешь,в каком спорте важнее талант чем упорный труд?", category: .sport),
        Question(question: "Какой спортсмен завоевал олимпийское золото?", category: .sport),
        Question(question: "Как ты относишься к командным видам спорта?", category: .sport),
        Question(question: "Какие привычки помогают тебе оставаться в хорошей физической форме?", category: .sport),
        Question(question: "Какие виды единоборств вы знаете?", category: .sport),
        Question(question: "Какие знаменитые футболисты вам известны?", category: .sport),
        Question(question: "Какие спортивные игры можно играть с мячом?", category: .sport),
        Question(question: "Какие Олимпийские виды спорта вы можете назвать?", category: .sport),
        Question(question: "Какие упражнения помогают развить выносливость?", category: .sport),
        Question(question: "Какие зимние виды спорта вам известны?", category: .sport),
        Question(question: "Какие страны сильны в футболе?", category: .sport),
        Question(question: "Какие спортивные инвентари нужны для тенниса?", category: .sport),
        Question(question: "Какие виды лёгкой атлетики вы знаете?", category: .sport),
        //Life
        Question(question: "Как ты любишь проводить свободное время?", category: .life),
        Question(question: "Чему бы ты хотел научиться в ближайшее время?", category: .life),
        Question(question: "Какой самый важный выбор ты сделал в жизни?", category: .life),
        Question(question: "Каким ты видишь свое будущее через 10 лет?", category: .life),
        Question(question: "Что делает тебя по-настоящему счастливым?", category: .life),
        Question(question: "Какие моменты в жизни делают вас счастливыми?", category: .life),
        Question(question: "Какие ценности для вас важны?", category: .life),
        Question(question: "Какие жизненные уроки вы усвоили?", category: .life),
        Question(question: "Какие мечты у вас есть?", category: .life),
        Question(question: "Какие качества помогают добиваться успеха?", category: .life),
        Question(question: "Какие вещи делают жизнь интереснее?", category: .life),
        Question(question: "Какие традиции есть в вашей семье?", category: .life),
        Question(question: "Какие привычки помогают быть здоровым?", category: .life),
        Question(question: "Какие события изменили вашу жизнь?", category: .life),
        Question(question: "Какие цели вы хотите достичь?", category: .life),
        //Celebrities
        Question(question: "Какая знаменитость, достигла успеха честным путем?", category: .celebrities),
        Question(question: "Какие знаменитости занимаются благотворительностью?", category: .celebrities),
        Question(question: "Какая знаменитость могла стала политиком?", category: .celebrities),
        Question(question: "Какой актер идеально подходит для своих ролей?", category: .celebrities),
        Question(question: "Знаменитости со своим брендом вещей?", category: .celebrities),
        Question(question: "Какие актёры вам нравятся?", category: .celebrities),
        Question(question: "Какие известные певцы вам известны?", category: .celebrities),
        Question(question: "Какие певцы популярны в мире?", category: .celebrities),
        Question(question: "Какие режиссёры сняли культовые фильмы?", category: .celebrities),
        Question(question: "Какие блогеры вам интересны?", category: .celebrities),
        Question(question: "Какие звёзды выиграли “Оскар”?", category: .celebrities),
        Question(question: "Какие знаменитости известны своим стилем?", category: .celebrities),
        Question(question: "Какие художники оставили след в истории?", category: .celebrities),
        Question(question: "Какие политики стали известны во всём мире?", category: .celebrities),
        Question(question: "Какие знаменитости имеют фонды поддержки?", category: .celebrities),
        //Movies and Art
        Question(question: "Какой фильм снят по книге?", category: .moviesAndArt),
        Question(question: "Как ты относишься к ремейкам классических фильмов?", category: .moviesAndArt),
        Question(question: "Какой фильм заставил тебя задуматься о жизни?", category: .moviesAndArt),
        Question(question: "Какие фильмы, по-твоему, стоит посмотреть каждому?", category: .moviesAndArt),
        Question(question: "Какой фильм имеет самый неожиданный финал?", category: .moviesAndArt),
        Question(question: "Какие фильмы вам нравятся?", category: .moviesAndArt),
        Question(question: "Какие жанры кино вы предпочитаете?", category: .moviesAndArt),
        Question(question: "Какие фильмы стали культовыми?", category: .moviesAndArt),
        Question(question: "Какие экранизации книг вам понравились?", category: .moviesAndArt),
        Question(question: "Какие мультфильмы можно смотреть в любом возрасте?", category: .moviesAndArt),
        Question(question: "Какие фильмы вас вдохновляют?", category: .moviesAndArt),
        Question(question: "Какие кинозлодеи самые запоминающиеся?", category: .moviesAndArt),
        Question(question: "Какие режиссёры создали великие фильмы?", category: .moviesAndArt),
        Question(question: "Какие фильмы стоит посмотреть хотя бы раз в жизни?", category: .moviesAndArt),
        
        Question(question: "Каких художники 20-х годов ты знаешь ?", category: .moviesAndArt),
        Question(question: "Какую музыку, по-твоему, можно считать искусством?", category: .moviesAndArt),
        Question(question: "Какое самое необычное произведение искусства ты встречал?", category: .moviesAndArt),
        Question(question: "Как бы ты описал искусство человеку, который никогда с ним не сталкивался?", category: .moviesAndArt),
        Question(question: "Какой художественный музей ты мечтаешь посетить?", category: .moviesAndArt),
        Question(question: "Какие художники вам нравятся?", category: .moviesAndArt),
        Question(question: "Какие направления в искусстве вам интересны?", category: .moviesAndArt),
        Question(question: "Какие картины вам запомнились?", category: .moviesAndArt),
        Question(question: "Какие музеи стоит посетить?", category: .moviesAndArt),
        Question(question: "Какие скульптуры произвели на вас впечатление?", category: .moviesAndArt),
        Question(question: "Какие произведения искусства изменили историю?", category: .moviesAndArt),
        Question(question: "Какие виды искусства вам ближе всего?", category: .moviesAndArt),
        Question(question: "Какие современные художники вам известны?", category: .moviesAndArt),
        Question(question: "Какие архитектурные здания вдохновляют вас?", category: .moviesAndArt),
        Question(question: "Какие искусства развиваются в последние десятилетия?", category: .moviesAndArt),
        //Nature
        Question(question: "Как природа меняется в разное время года в твоем регионе?", category: .nature),
        Question(question: "Какие моря есть в мире ?", category: .nature),
        Question(question: "Какой заповедник или национальный парк ты хотел бы посетить?", category: .nature),
        Question(question: "Какие природные катаклизмы тебя пугают?", category: .nature),
        Question(question: "Какое самое необычное животное ты встречал в природе?", category: .nature),
        Question(question: "Какие растения вам нравятся?", category: .nature),
        Question(question: "Какие природные явления вас поражают?", category: .nature),
        Question(question: "Какие леса или горы вы бы хотели посетить?", category: .nature),
        Question(question: "Какие реки или озёра вам известны?", category: .nature),
        Question(question: "Какие экосистемы вам наиболее впечатляют?", category: .nature),
        Question(question: "Какие природные ресурсы считаются важными для человечества?", category: .nature),
        Question(question: "Какие национальные парки стоит посетить?", category: .nature),
        Question(question: "Какие виды растений можно встретить дома?", category: .nature),
        Question(question: "Какие виды растений можно встретить в вашем регионе?", category: .nature),
        Question(question: "Какие изменения в природе вы замечаете в последнее время?", category: .nature),
        
    ]
    
}



//static let questions: [Question] = [
//    
//    //General
//    Question(question: "Какой твой самый неожиданный талант?", category: .general),
//    Question(question: "Какое важное жизненное правило ты для себя установил?", category: .general),
//    Question(question: "Что для тебя значит успех?", category: .general),
//    Question(question: "Как ты справляешься со стрессом?", category: .general),
//    Question(question: "Какая у тебя мечта, о которой пока мало кто знает?", category: .general),
//    Question(question: "Какие страны вы хотели бы посетить?", category: .general),
//    Question(question: "Какие книги вам нравятся?", category: .general),
//    Question(question: "Какие животные живут в джунглях?", category: .general),
//    Question(question: "Какие фрукты вы любите?", category: .general),
//    Question(question: "Какие фильмы можно пересматривать снова и снова?", category: .general),
//    Question(question: "Какие музыкальные жанры вам известны?", category: .general),
//    Question(question: "Какие качества важны в друге?", category: .general),
//    Question(question: "Какие праздники отмечают в разных странах?", category: .general),
//    Question(question: "Какие известные изобретения изменили мир?", category: .general),
//    Question(question: "Какие языки вы знаете?", category: .general),
//    // Sport
//    Question(question: "Как есть виды восстанавления после тренировок?", category: .sport),
//    Question(question: "Как ты считаешь,в каком спорте важнее талант чем упорный труд?", category: .sport),
//    Question(question: "Какой спортсмен завоевал олимпийское золото?", category: .sport),
//    Question(question: "Как ты относишься к командным видам спорта?", category: .sport),
//    Question(question: "Какие привычки помогают тебе оставаться в хорошей физической форме?", category: .sport),
//    Question(question: "Какие виды единоборств вы знаете?", category: .sport),
//    Question(question: "Какие знаменитые футболисты вам известны?", category: .sport),
//    Question(question: "Какие спортивные игры можно играть с мячом?", category: .sport),
//    Question(question: "Какие Олимпийские виды спорта вы можете назвать?", category: .sport),
//    Question(question: "Какие упражнения помогают развить выносливость?", category: .sport),
//    Question(question: "Какие зимние виды спорта вам известны?", category: .sport),
//    Question(question: "Какие страны сильны в футболе?", category: .sport),
//    Question(question: "Какие спортивные инвентари нужны для тенниса?", category: .sport),
//    Question(question: "Какие виды лёгкой атлетики вы знаете?", category: .sport),
//    //Life
//    Question(question: "Как ты любишь проводить свободное время?", category: .life),
//    Question(question: "Чему бы ты хотел научиться в ближайшее время?", category: .life),
//    Question(question: "Какой самый важный выбор ты сделал в жизни?", category: .life),
//    Question(question: "Каким ты видишь свое будущее через 10 лет?", category: .life),
//    Question(question: "Что делает тебя по-настоящему счастливым?", category: .life),
//    Question(question: "Какие моменты в жизни делают вас счастливыми?", category: .life),
//    Question(question: "Какие ценности для вас важны?", category: .life),
//    Question(question: "Какие жизненные уроки вы усвоили?", category: .life),
//    Question(question: "Какие мечты у вас есть?", category: .life),
//    Question(question: "Какие качества помогают добиваться успеха?", category: .life),
//    Question(question: "Какие вещи делают жизнь интереснее?", category: .life),
//    Question(question: "Какие традиции есть в вашей семье?", category: .life),
//    Question(question: "Какие привычки помогают быть здоровым?", category: .life),
//    Question(question: "Какие события изменили вашу жизнь?", category: .life),
//    Question(question: "Какие цели вы хотите достичь?", category: .life),
//    //Celebrities
//    Question(question: "Какая знаменитость, достигла успеха честным путем?", category: .celebrities),
//    Question(question: "Какие знаменитости занимаются благотворительностью?", category: .celebrities),
//    Question(question: "Какая знаменитость могла стала политиком?", category: .celebrities),
//    Question(question: "Какой актер идеально подходит для своих ролей?", category: .celebrities),
//    Question(question: "Знаменитости со своим брендом вещей?", category: .celebrities),
//    Question(question: "Какие актёры вам нравятся?", category: .celebrities),
//    Question(question: "Какие известные певцы вам известны?", category: .celebrities),
//    Question(question: "Какие певцы популярны в мире?", category: .celebrities),
//    Question(question: "Какие режиссёры сняли культовые фильмы?", category: .celebrities),
//    Question(question: "Какие блогеры вам интересны?", category: .celebrities),
//    Question(question: "Какие звёзды выиграли “Оскар”?", category: .celebrities),
//    Question(question: "Какие знаменитости известны своим стилем?", category: .celebrities),
//    Question(question: "Какие художники оставили след в истории?", category: .celebrities),
//    Question(question: "Какие политики стали известны во всём мире?", category: .celebrities),
//    Question(question: "Какие знаменитости имеют фонды поддержки?", category: .celebrities),
//    //Movies and Art
//    Question(question: "Какой фильм снят по книге?", category: .moviesAndArt),
//    Question(question: "Как ты относишься к ремейкам классических фильмов?", category: .moviesAndArt),
//    Question(question: "Какой фильм заставил тебя задуматься о жизни?", category: .moviesAndArt),
//    Question(question: "Какие фильмы, по-твоему, стоит посмотреть каждому?", category: .moviesAndArt),
//    Question(question: "Какой фильм имеет самый неожиданный финал?", category: .moviesAndArt),
//    Question(question: "Какие фильмы вам нравятся?", category: .moviesAndArt),
//    Question(question: "Какие жанры кино вы предпочитаете?", category: .moviesAndArt),
//    Question(question: "Какие фильмы стали культовыми?", category: .moviesAndArt),
//    Question(question: "Какие экранизации книг вам понравились?", category: .moviesAndArt),
//    Question(question: "Какие мультфильмы можно смотреть в любом возрасте?", category: .moviesAndArt),
//    Question(question: "Какие фильмы вас вдохновляют?", category: .moviesAndArt),
//    Question(question: "Какие кинозлодеи самые запоминающиеся?", category: .moviesAndArt),
//    Question(question: "Какие режиссёры создали великие фильмы?", category: .moviesAndArt),
//    Question(question: "Какие фильмы стоит посмотреть хотя бы раз в жизни?", category: .moviesAndArt),
//    
//    Question(question: "Каких художники 20-х годов ты знаешь ?", category: .moviesAndArt),
//    Question(question: "Какую музыку, по-твоему, можно считать искусством?", category: .moviesAndArt),
//    Question(question: "Какое самое необычное произведение искусства ты встречал?", category: .moviesAndArt),
//    Question(question: "Как бы ты описал искусство человеку, который никогда с ним не сталкивался?", category: .moviesAndArt),
//    Question(question: "Какой художественный музей ты мечтаешь посетить?", category: .moviesAndArt),
//    Question(question: "Какие художники вам нравятся?", category: .moviesAndArt),
//    Question(question: "Какие направления в искусстве вам интересны?", category: .moviesAndArt),
//    Question(question: "Какие картины вам запомнились?", category: .moviesAndArt),
//    Question(question: "Какие музеи стоит посетить?", category: .moviesAndArt),
//    Question(question: "Какие скульптуры произвели на вас впечатление?", category: .moviesAndArt),
//    Question(question: "Какие произведения искусства изменили историю?", category: .moviesAndArt),
//    Question(question: "Какие виды искусства вам ближе всего?", category: .moviesAndArt),
//    Question(question: "Какие современные художники вам известны?", category: .moviesAndArt),
//    Question(question: "Какие архитектурные здания вдохновляют вас?", category: .moviesAndArt),
//    Question(question: "Какие искусства развиваются в последние десятилетия?", category: .moviesAndArt),
//    //Nature
//    Question(question: "Как природа меняется в разное время года в твоем регионе?", category: .nature),
//    Question(question: "Какие моря есть в мире ?", category: .nature),
//    Question(question: "Какой заповедник или национальный парк ты хотел бы посетить?", category: .nature),
//    Question(question: "Какие природные катаклизмы тебя пугают?", category: .nature),
//    Question(question: "Какое самое необычное животное ты встречал в природе?", category: .nature),
//    Question(question: "Какие растения вам нравятся?", category: .nature),
//    Question(question: "Какие природные явления вас поражают?", category: .nature),
//    Question(question: "Какие леса или горы вы бы хотели посетить?", category: .nature),
//    Question(question: "Какие реки или озёра вам известны?", category: .nature),
//    Question(question: "Какие экосистемы вам наиболее впечатляют?", category: .nature),
//    Question(question: "Какие природные ресурсы считаются важными для человечества?", category: .nature),
//    Question(question: "Какие национальные парки стоит посетить?", category: .nature),
//    Question(question: "Какие виды растений можно встретить дома?", category: .nature),
//    Question(question: "Какие виды растений можно встретить в вашем регионе?", category: .nature),
//    Question(question: "Какие изменения в природе вы замечаете в последнее время?", category: .nature),
//    
//]
